export const WORKFLOW_STEPS = [
  "currentPage",
  "pageStack",
  "pageData",
  "systemInfo",
  "appGlobalData",
  "launchOptions",
  "navigateTo",
  "reLaunch",
  "switchTab",
  "wait",
  "query",
  "snapshot",
  "tap",
  "longpress",
  "input",
  "elementText",
  "elementValue",
  "elementAttribute",
  "elementProperty",
  "elementTrigger",
  "elementScreenshot",
  "callWxMethod",
  "mockWxMethod",
  "restoreWxMethod",
  "storageGet",
  "storageSet",
  "storageRemove",
  "storageClear",
  "setPageData",
  "callPageMethod",
  "pageSize",
  "scrollTop",
  "pageScrollTo",
  "evaluate",
  "screenshot",
  "startConsole",
  "listConsole",
  "clearConsole",
  "networkInstall",
  "networkList",
  "networkClear",
  "networkRestore",
  "mediaInstall",
  "mediaList",
  "mediaAction",
];

export function getCapabilities() {
  return {
    ok: true,
    command: "capabilities",
    package: {
      name: "vince-mp-cli",
      version: "0.1.0",
      backend: "miniprogram-automator",
    },
    commands: [
      "help",
      "capabilities",
      "doctor",
      "smoke-existing",
      "run",
      "screenshot",
      "media",
    ],
    workflowSteps: WORKFLOW_STEPS,
    connectionModes: {
      attach: {
        required: ["wsEndpoint"],
        sideEffects: ["connect-existing-automation-session"],
        forbidden: ["projectPath", "launch", "reLaunch"],
      },
      launch: {
        required: ["projectPath"],
        sideEffects: ["may-open-or-focus-devtools-project"],
      },
    },
    safeDefaults: {
      implicitLaunch: false,
      implicitRelaunch: false,
      implicitNetworkInstrumentation: false,
      implicitMediaInstrumentation: false,
      implicitFileWrites: false,
      cameraCapture: "metadata-only unless explicitly requested",
      output: "json",
    },
    importantErrors: [
      "PATH_OUTSIDE_WORKSPACE",
      "UNSAFE_CONNECTION_MODE",
      "AUTOMATOR_CONNECT_FAILED",
      "SNAPSHOT_ELEMENT_ENUMERATION_TIMEOUT",
      "STALE_OR_UNKNOWN_UID",
      "UNSAFE_WX_METHOD",
      "STORAGE_CLEAR_REQUIRES_CONFIRMATION",
      "CAMERA_MOCK_REQUIRES_FIXTURE",
    ],
  };
}
